### ISSUE TITLE
Can't exclude elements from being affected by dark-mode

### ISSUE THREAD

**Issue by zandalartribe** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#15]
**Describe the bug**
None of the provided options for skipping dark-mode for specific elements are working for me (classname, CSS rules).

**To Reproduce**
1. Install and activate plugin
2. Test that it correctly allows you to switch between light and dark mode
3. Add class `darkmode-ignore` to an element
4. The element still gets switched
5. Add CSS rule `mix-blend-mode: difference;` to the element
6. The element still gets switched

I've checked that the markup/CSS is definitely being updated and not cached.

**Expected behavior**
The chosen element(s) should not be affected by the dark-mode filter.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser: Brave (Chromium)

**Additional context**
A previous issue also references being able to select not to apply dark mode to images, but that seems to be missing from the plugin config as well, and my images are being color-flipped by default. _Edit: It seems to be inconsistent in how it's affecting images - some are flipped, but some others (WP uploads) aren't._

**Comment by JoseSoteloCohen** [comment]
Hello @zandalartribe 

Thank you so much for taking the time to leave an issue, it helps a lot.

Would you mind posting here your website or sending it to soporte@inboundlatino.com?

The options work as expected, but there are some specific cases where the plugin needs custom code to work, mostly because of the way of how mixe-blend-mode:difference works.

Hope we can make it work.

Cheers!

**Comment by zandalartribe** [comment]
Hey - the website is [www.zandalartribe.eu](https://www.zandalartribe.eu/), but the plugin isn't activated on the live site.

**Comment by JoseSoteloCohen** [comment]
OK, will try and see if I can fix it without it being installed, but kind of doubt it. If you can create a staging site with the plugin activated that would be nice, because if I can't replicate the issue there's no way to find a solution @zadalartribe

**Comment by JoseSoteloCohen** [comment]
Hello @zandalartribe if I can't replicate the issue there's no way for me to solve it :(

If at some point you can enable it on a replicated version of your site let me know and I will check it out.

Cheers!

**Comment by theAkito** [comment]
@JoseSoteloCohen 
Exactly the same issue with [Crayon Syntax Highlighter](https://github.com/aramk/crayon-syntax-highlighter). Disabling for normal paragraphs work, but it still inverts code blocks. It's a pity as your dark mode is the best plugin of all the ones I could find as a result of the Wordpress plugin search. Just this one thing is super important and has to be fixed.
Any idea about what I can do?
I don't know much about CSS and browser front-end.
