### ISSUE TITLE
Elements loaded with AJAX does not have darkmode-ignore.

### ISSUE THREAD

**Issue by dm00z** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#16]
**Describe the bug**
Same with title. For example, images loaded with AJAX lack `darkmode-ignore` class

**To Reproduce**
1. Turn dark mode on
2. Load some elements with AJAX

**Expected behavior**
Elements have `darkmode-ignore` class

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Mojave 10.14.6
 - Browser: Chrome
 - Version: 77

**Smartphone (please complete the following information):**
 - Device: iPhoneXS
 - OS: 13.1.3
 - Browser: Chrome, Safari
 - Version: Chrome 78

**Comment by JoseSoteloCohen** [comment]
Hello @dm00z !

Sadly, there's no way to add a class to an AJAX element because it isn't in the DOM when the widget is activated.

I guess that you would make it work with some jquery, if you want leave here the website URL and I'll take a look.
