### ISSUE TITLE
Remove Icon, When Auto Match OS

### ISSUE THREAD

**Issue by designaa** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#17]
Hi,

Thanks so much for this plugin! I do have one feature request: be able to show no icon. Specifically I want to use this feature when I auto match OS. Right now I only want to auto match OS but there’s the icon still there and I would like for it not to be and only use the plugin to do auto match OS. 

Thank you for considering.

**Comment by JoseSoteloCohen** [comment]
Hello @designaa !

You want to remove the whole widget?

**Comment by designaa** [comment]
Yes, I would like the option to remove the whole widget when auto match is enabled. And just use the plugin to auto match OS. I hope this is a possibility. Thank you.

**Comment by neyhsu** [comment]
Remove Icon, When Auto Match OS .....needed...

**Comment by JoseSoteloCohen** [comment]
You will be able to do this in version 2.0.0 which I'm about to release :)

You just need to check the last checkbox called: Want to use your own toggle widget or button?
