### ISSUE TITLE
wordpress shortcode

### ISSUE THREAD

**Issue by BenfishDesign** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#18]
Hi, does this got any shortcode? we wan to rearrange the button location..

**Comment by JoseSoteloCohen** [comment]
@BenfishDesign Hello!

No, it doesn't.

But I'm going to release a feature that will allow you to use anything with the class "darkmode-enable" to trigger the dark mode, so you could create your own widget, use text or even an icon in the menu.
