### ISSUE TITLE
Ability to add elements to ignore

### ISSUE THREAD

**Issue by MrJoax** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#19]
I use the enfold theme and in my standard design the footer and some other elements already have a dark color scheme.. 

I probably can fix this in css myself but it would be a nice addition to the settings screen if I could just list some elements the plugin ignores..

With images I have a similar issue.. if you look here https://www.arendmaatkamp.nl/over-arend/
My jpg portrait a little bit down the page doesn’t get ignored.. while I did add the ignore class to this element in the backend.. which works when the image gets loaded in the background.. but not on regular images.. funny thing is that the jpgs are in negative.. but the pngs are not.. this should be the other way around in my case because I use flat black illustrations only as pngs especially because I want to cleanly switch to darkmode

Excuses me if my thoughts are a bit chaotic.. I’m an artist 😅😜

**Comment by estebanhirzfeld** [comment]
same

**Comment by JoseSoteloCohen** [comment]
Hello @MrJoax 

I checked it out and tried to make it work but was unable to do it, I'll keep looking into it, but this happens with some themes or page builders as something similar occurs with Divi themes.

I'm sorry, when I have more time will try to see what is happening but at this point I haven't been able to find the cause.

Cheers!

**Comment by JoseSoteloCohen** [comment]
Seems that some themes and page builder do not work well with the technology used by the plugin.

This could be caused by their HTML outputs or even by how the page was created (too many nesting divs).

Until now I've seen this on:

- Divi.
- Thrive Architect.
- Enfold.
