### ISSUE TITLE
Background color change of original theme

### ISSUE THREAD

**Issue by BrownBurger** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#21]
Hi there,

I use the „Twenty Twenty“ theme with #f5efe0 as the background-color. However, when I activate this plugin, the background color changes to completely white which is not what I want..

**Comment by JoseSoteloCohen** [comment]
@BrownBurger Hello!

Will look into this!

Thank you for reaching out

**Comment by BrownBurger** [comment]
Works now fine with 2.0.4. Thank you!
