### ISSUE TITLE
Images becoming negative

### ISSUE THREAD

**Issue by Kafesism** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#23]
**Is your feature request related to a problem? Please describe.**
Its a great plugin. Very usefull. However when I or users toggle it, the images become negative aswell but the images are an integral part of my website. [http://conquerorsabacus.online/](url)

**Describe the solution you'd like**
 I feel this is not necessary for dark mode to change images. Either a way to exclude certain elements from the plugin or an option to complete ignore all images should work.

**Additional context**
It still works very well and I'm thankfull for your work. This is my only issue so far.

**Comment by Ikennaf1** [comment]
hi @Kafesism , have you found a solution yet? If not, can you give this plugin a try? [https://github.com/Ikennaf1/blinds](https://github.com/Ikennaf1/blinds)

**Comment by JoseSoteloCohen** [comment]
Hello @Kafesism 

Checking the URL you gave me, what you need to do is add the class darkmode-ignore to the section and column in which the image is placed,

Here is an example of the HTML element in which you have to place it:
![image](https://user-images.githubusercontent.com/12568016/92285056-fdf84e80-eec8-11ea-9299-77bcbe309503.png)

I don't know how it's built so I can't give you a more specific recommendation, but just try to add that class to the elements containing the image and it should do the trick.

Let me know if you can solve it!

Chees!

**Comment by JoseSoteloCohen** [comment]
Didn't get a reply for a couple of months.
