### ISSUE TITLE
Can't set up button size

### ISSUE THREAD

**Issue by kpspu** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#24]
**Describe the bug**
It doesn't matter how I adjust "Button size" and "Icon size", the button still huge. I even was forced to place it -30px left and right to see only 1/4 of the controller.

**To Reproduce**
1. Set Button size on the MIN
2. Set Icon size on the MIN
3. See the result on your blog
4. The button is huge

**Expected behavior**
Something with scrollers, I think, might be needed some adjustment.

**Screenshots**
![ScreenClip](https://user-images.githubusercontent.com/32261191/92511802-843cc980-f216-11ea-95f8-67b990b8a7bc.png)
![ScreenClip](https://user-images.githubusercontent.com/32261191/92511849-90288b80-f216-11ea-9194-e473239569cd.png)

**Wordpress (please complete the following information):**
 - WP Version: 5.5.1
 - Browser Chromium
 - Browser Version 85.0.564.44 (Official build) (64-bit)

**Additional context**
I had this problem since I installed the plugin one year ago. But after the last plugin update, the problem was exaggerated.

**Comment by JoseSoteloCohen** [comment]
Hello @k-slava 

Please share the URL so I can take a look :)

**Comment by kpspu** [comment]
> Hello @k-slava
> 
> Please share the URL so I can take a look :)

With a pleasure :)
https://llewm.com/

**Comment by JoseSoteloCohen** [comment]
@k-slava 

Just add this in your style.css file:

.darkmode-toggle {
    width: 50px !important;
    height: 50px !important;
}

That should do the trick.

Let me know if it works.

**Comment by kpspu** [comment]
Thanks, it works!
But not quite. It is still big, as it was before the update. I will be happy if it might be smaller.
![ScreenClip](https://user-images.githubusercontent.com/32261191/92638648-422d8980-f2e3-11ea-9a85-8dd74a0a7cb0.png)

UPD: I found. I just need to set up width and height smaller than 50px

**Comment by kpspu** [comment]
Thank you for your help!
