### ISSUE TITLE
The button is too big!!!!!!!!!

### ISSUE THREAD

**Issue by MrCatzzz** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#25]
**Describe the bug**

The button is too big for the website. I downloaded the plugin for my WordPress website and made it as small as I could in the setting.  It takes up 1/4th of the screen for mobile users.

**To Reproduce**
Step 1: Download the plugin. 

Step 2: Suffer.

**Expected behavior**
It not to take 1/4th the screen.

Here is the website itself. 
https://cherryoutrage.com/2020/11/21/chapter-list-2/

**Comment by Yourlaks** [comment]
Hi, 

You can use this class to manually change the icon size:

.darkmode-toggle {
    width: 46px !important;
    height: 46px !important;
}

**Comment by JoseSoteloCohen** [comment]
Seems that you are now using another plugin, thanks for trying out mine anyway. @MrCatzzz 

Thanks for the help @Yourlaks 

Cheers!

**Comment by MrCatzzz** [comment]
Hello Hello,

Sorry about not responding till now. Is there a way to make the smaller? I
put your widget back up on the website. I would really like to use it if I
can. Thank you!

**Comment by JoseSoteloCohen** [comment]
@MrCatzzz did you try this?
`.darkmode-toggle {
width: 60px !important;
height: 60px !important;
}`

You can add it to the CSS section in the customizer of your theme.
