### ISSUE TITLE
Images and header affected, even with darkmode-ignore

### ISSUE THREAD

**Issue by sjvanarendonk** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#27]
Hello Jose,

Im using this plugin in combination with the minimal portfolio theme (https://abileweb.com/portfolio/minimal-portfolio/).
After installing, the plugin adds the darkmode-ignore class to images on the page (as intended), but when the button is toggled the images are still inverted. The same goes for the header-menu when it is set to sticky.

I've tested it on a clean install of wordpress with the theme and plugin only, the result is the same. It should be simple enough the replicate. Does this have to do with the theme or is it the plugin?

Hope to hear from you soon!

**Comment by JoseSoteloCohen** [comment]
Hello @SJArendonk 

Thank you for reaching out.

I tried it out and didn't get the same behavior, if you could give me access to the site (staging) where you are experiencing this that would be great.

If you can't, could you add screenshots or something so I can see the issue?

**Comment by sjvanarendonk** [comment]
Hello again,

I unfortunately cant grant you access to the site as its on a local machine, I have exported the site and uploaded it to drive so that you may check it out for yourself: https://drive.google.com/file/d/1FSxrVp1fiw7l7GM9B2jr32_DKDgGFvhL/view?usp=sharing

I have also taken 3 screenshots showing the issue:
Before enabling nightmode: https://imgur.com/MHclXnA
After enabling nightmode: https://imgur.com/edSBhv8
After enabling nightmode and scrolling down (sticky header enabled): https://i.imgur.com/iQEORHO

Hope this will be enough to provide you a sense of the issue, let me know if you need anything else.

**Comment by JoseSoteloCohen** [comment]
HI @SJArendonk 

That image is a background image, so the plugin won't be able to exclude it. You would need custom code (CSS or JavaScript) to make it work by increasing the z-index when darkmode is enabled, or something similar.

The issue with sticky is similar, as sticky bars are placed on top of everything and in this case it's on top of the layer that darkmode adds to give the black effects, that's because even when enabled it's still white.

Sadly, this isn't an actual bug but the normal behavior of the plugin, I know it's limited and in cases like this it requires more custom work than expected, but that's the downside of the approach used to create it.

**Comment by sjvanarendonk** [comment]
That makes sense. Simply giving the image a z-index higher than that of the darkmode layer doesnt appear to fix the issue however, am I doing something wrong here?

**Comment by JoseSoteloCohen** [comment]
Could you try adding this to your child theme styles or in the CSS section of the customizer?

![image](https://user-images.githubusercontent.com/12568016/103416840-56c5b400-4b56-11eb-9b92-53142c414e9c.png)


`.darkmode-background{
  z-index: 0 !important;
}`

If you want to exclude the text of the jumbotron of your blog posts:

`.darkmode--activated #page > section > div > div > div > div > h2{ 
	mix-blend-mode: difference; 
}`

If you want to exclude the whole jumbotron:
`.darkmode--activated .page-header.jumbotron { 
	mix-blend-mode: difference; 
}`

Let me know if that works.

**Comment by sjvanarendonk** [comment]
Yes this has largely resolved my issue. I suppose for the remaining little things ill just have to tinker a bit. Thanks a bunch!
