### ISSUE TITLE
Invert colors of WordPress theme header 

### ISSUE THREAD

**Issue by sam-ankerspace** [JoseSoteloCohen/Blackout-WordPress-Dark-mode-Widget#30]
The WordPress theme header gets ignored for inverting colors. Is there a way to tweak the code so it inverts colors of an wordpress theme header too?

**Comment by JoseSoteloCohen** [comment]
Hello @sam-ankerspace 

In order to help you I'll need to take a look at the website with the plugin enabled, is that possible?

You can send it to jose@inboundlatino.com if you don't want to share it here.

**Comment by sam-ankerspace** [comment]
Hello Jose,

thank you for the fast reply. I have sent you an e-mail.

The Blackout: Dark Mode Widget for WordPress Plugin is awesome!

Kind regards,
Sam
